CREATE TABLE atlas_athletes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    age INTEGER NOT NULL,
    gender TEXT NOT NULL,
    weight INTEGER NOT NULL
);

ALTER TABLE atlas_lifts
    ADD COLUMN
        athlete_id INTEGER REFERENCES atlas_athletes(id)
        ON DELETE SET NULL;