CREATE TABLE atlas_events (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL
);

ALTER TABLE atlas_athletes
    ADD COLUMN
        event_id INTEGER REFERENCES atlas_events(id)
        ON DELETE SET NULL;

ALTER TABLE atlas_lifts
    ADD COLUMN
        event_id INTEGER REFERENCES atlas_events(id)
        ON DELETE SET NULL;