CREATE TABLE atlas_competitions (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL
);

ALTER TABLE atlas_athletes
    ADD COLUMN
        competition_id INTEGER REFERENCES atlas_competitions(id)
        ON DELETE SET NULL;

ALTER TABLE atlas_lifts
    ADD COLUMN
        competition_id INTEGER REFERENCES atlas_competitions(id)
        ON DELETE SET NULL;